#!/usr/bin/env bash


TITLE='pravega_container'
IMAGE='pravegasensorcollector:latest'


ENVVARS=("PRAVEGA_SENSOR_COLLECTOR_LEAP1_CLASS=io.pravega.sensor.collector.leap.LeapDriver"
"PRAVEGA_SENSOR_COLLECTOR_LEAP1_API_URI=http://127.0.0.1:8083"
"PRAVEGA_SENSOR_COLLECTOR_LEAP1_USERNAME=admin"
"PRAVEGA_SENSOR_COLLECTOR_LEAP1_PASSWORD=mypassword"
"PRAVEGA_SENSOR_COLLECTOR_LEAP1_POLL_PERIOD_SEC=180"
"PRAVEGA_SENSOR_COLLECTOR_LEAP1_PERSISTENT_QUEUE_FILE=/tmp/leap1.db"
"PRAVEGA_SENSOR_COLLECTOR_LEAP1_PERSISTENT_QUEUE_CAPACITY_EVENTS=10000"
"PRAVEGA_SENSOR_COLLECTOR_LEAP1_SCOPE=examples"
"PRAVEGA_SENSOR_COLLECTOR_LEAP1_CREATE_SCOPE=true"
"PRAVEGA_SENSOR_COLLECTOR_LEAP1_STREAM=leap"
"PRAVEGA_SENSOR_COLLECTOR_LEAP1_ROUTING_KEY=routingkey1"
"PRAVEGA_SENSOR_COLLECTOR_LEAP1_EXACTLY_ONCE=true"
"PRAVEGA_SENSOR_COLLECTOR_LEAP1_PRAVEGA_CONTROLLER_URI=tcp://127.0.0.1:9090"
"PRAVEGA_SENSOR_COLLECTOR_LEAP1_TRANSACTION_TIMEOUT_MINUTES=2.0" )

CONTAINER=${TITLE}

declare -a ENVVAR_STRING
for envvar in ${ENVVARS[@]} ; do
  ENVVAR_STRING+=("-e ${envvar}")
done

NAME_STRING="--name ${CONTAINER}"

OPTS="${ENVVAR_STRING[@]} $NAME_STRING"

docker build --pull --rm -f "Dockerfile" -t $IMAGE "."
docker run $OPTS $IMAGE

# THE_COMMAND="docker run $OPTS $IMAGE"
# echo "$THE_COMMAND"
# exec $THE_COMMAND
